const express=require('express');
const dayjs=require('dayjs');
const fs=require('fs');
const path=require('path');
const {db}=require('../db/init');
const {requireAnyAuth,requireRole}=require('../middleware/auth');
const {notifyUser,safeUrl,configured}=require('../services/notificationService');
const {getPitisNotificationAutomationSettings,setPitisNotificationAutomationSettings}=require('../services/portalSettingsService');
const router=express.Router();
function getPitisApkPath(){
  if(process.env.PITIS_APK_PATH)return path.resolve(process.env.PITIS_APK_PATH);
  const databasePath=path.resolve(process.env.DB_PATH||path.join(process.cwd(),'data.db'));
  return path.join(path.dirname(databasePath),'distribution','PITIS.apk');
}
function getPitisApkStatus(){
  const apkPath=getPitisApkPath();
  try{const stat=fs.statSync(apkPath);return{available:stat.isFile(),size:stat.size,updatedAt:stat.mtime.toISOString()}}catch(_error){return{available:false,size:0,updatedAt:null}}
}
router.use(requireAnyAuth);
router.get('/api/notifications',(req,res)=>{const limit=Math.min(100,Math.max(1,+req.query.limit||30)),before=+req.query.before||Number.MAX_SAFE_INTEGER;res.json({items:db.prepare('SELECT * FROM notifications WHERE user_id=? AND id<? ORDER BY id DESC LIMIT ?').all(req.session.user.id,before,limit),unread:db.prepare('SELECT COUNT(*) count FROM notifications WHERE user_id=? AND read_at IS NULL').get(req.session.user.id).count})});
router.patch('/api/notifications/:id/read',(req,res)=>{db.prepare('UPDATE notifications SET read_at=COALESCE(read_at,?) WHERE id=? AND user_id=?').run(dayjs().toISOString(),+req.params.id,req.session.user.id);res.json({ok:true})});
router.post('/api/notifications/mark-all-read',(req,res)=>{db.prepare('UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL').run(dayjs().toISOString(),req.session.user.id);res.json({ok:true})});
router.get('/api/push/public-key',(_req,res)=>res.json({publicKey:configured()?String(process.env.VAPID_PUBLIC_KEY):null}));
router.get('/api/push/subscriptions',(req,res)=>res.json(db.prepare('SELECT id,device_name,browser,platform,created_at,last_seen_at,enabled FROM push_subscriptions WHERE user_id=? ORDER BY updated_at DESC').all(req.session.user.id)));
router.post('/api/push/subscribe',(req,res)=>{const s=req.body.subscription||req.body,endpoint=String(s.endpoint||''),p256dh=String(s.keys?.p256dh||''),auth=String(s.keys?.auth||'');if(!endpoint.startsWith('https://')||!p256dh||!auth)return res.status(400).json({error:'Invalid push subscription.'});const now=dayjs().toISOString();db.prepare(`INSERT INTO push_subscriptions(user_id,endpoint,p256dh,auth,device_name,browser,platform,created_at,updated_at,last_seen_at,enabled) VALUES(?,?,?,?,?,?,?,?,?,?,1) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,device_name=excluded.device_name,browser=excluded.browser,platform=excluded.platform,updated_at=excluded.updated_at,last_seen_at=excluded.last_seen_at,enabled=1`).run(req.session.user.id,endpoint,p256dh,auth,String(req.body.device_name||'This browser').slice(0,120),String(req.body.browser||'').slice(0,80),String(req.body.platform||'').slice(0,80),now,now,now);res.json({ok:true})});
router.delete('/api/push/subscriptions/:id',(req,res)=>{db.prepare('DELETE FROM push_subscriptions WHERE id=? AND user_id=?').run(+req.params.id,req.session.user.id);res.json({ok:true})});
router.get('/api/notification-preferences',(req,res)=>{db.prepare('INSERT OR IGNORE INTO notification_preferences(user_id) VALUES(?)').run(req.session.user.id);res.json(db.prepare('SELECT * FROM notification_preferences WHERE user_id=?').get(req.session.user.id))});
router.patch('/api/notification-preferences',(req,res)=>{db.prepare('INSERT OR IGNORE INTO notification_preferences(user_id) VALUES(?)').run(req.session.user.id);const keys=['calendar_tag','calendar_event_time','calendar_3_days','calendar_5_days','reminder_assigned','reminder_due_soon','reminder_overdue','pitis_progress','pitis_0930_reminder','pitis_first_award','system_important'];for(const key of keys)if(Object.hasOwn(req.body,key))db.prepare(`UPDATE notification_preferences SET ${key}=? WHERE user_id=?`).run(req.body[key]?1:0,req.session.user.id);res.json({ok:true})});
router.post('/api/notifications/test',async(req,res)=>{const now=Date.now(),last=Number(req.session.lastPushTestAt||0);if(now-last<30000)return res.status(429).json({error:'Wait 30 seconds before sending another test notification.'});req.session.lastPushTestAt=now;const n=await notifyUser(req.session.user.id,{type:'system',title:'PITIS notification test',message:'Push notifications are working on this device.',url:'/notifications',entityType:'test',entityId:now},{dedupe:false});res.json({ok:true,id:n.id})});
router.get('/notifications',(req,res)=>res.render('notifications',{title:'Notifications'}));
router.get('/notification-settings',(req,res)=>res.render('notification-settings',{title:'Notification Settings'}));
router.get('/admin/notification-automation',requireRole('admin'),(req,res)=>res.render('admin-notification-automation',{title:'PITIS Notification Automation',settings:getPitisNotificationAutomationSettings(),saved:req.query.saved==='1',error:String(req.query.error||'')}));
router.post('/admin/notification-automation',requireRole('admin'),(req,res)=>{const time=String(req.body.no_award_time||'').trim();if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(time))return res.redirect('/admin/notification-automation?error='+encodeURIComponent('Enter a valid reminder time.'));setPitisNotificationAutomationSettings({noAwardEnabled:req.body.no_award_enabled==='on',noAwardTime:time,noAwardTitle:req.body.no_award_title,noAwardMessage:req.body.no_award_message,firstAwardEnabled:req.body.first_award_enabled==='on',winnerTitle:req.body.winner_title,winnerMessage:req.body.winner_message,peerTitle:req.body.peer_title,peerMessage:req.body.peer_message},req.session.user.id);res.redirect('/admin/notification-automation?saved=1')});
router.get('/admin/notification-users',requireRole('admin'),(req,res)=>{const users=db.prepare(`SELECT u.id,u.username,u.display_name,u.role,COUNT(ps.id) active_devices,(SELECT MAX(n.created_at) FROM notifications n WHERE n.user_id=u.id AND n.type='notification_setup_reminder') last_reminded_at FROM users u LEFT JOIN push_subscriptions ps ON ps.user_id=u.id AND ps.enabled=1 WHERE u.is_active=1 GROUP BY u.id ORDER BY active_devices ASC,u.display_name COLLATE NOCASE`).all();res.render('admin-notification-users',{title:'Notification Device Status',users,message:String(req.query.message||''),pitisApk:getPitisApkStatus()})});
router.get('/admin/notification-users/pitis.apk',requireRole('admin'),(_req,res)=>{const apkPath=getPitisApkPath();if(!getPitisApkStatus().available)return res.status(404).send('The signed PITIS APK has not been published yet.');res.setHeader('Cache-Control','private, no-store');res.type('application/vnd.android.package-archive');res.download(apkPath,'PITIS.apk')});
router.post('/admin/notification-users/:id/remind',requireRole('admin'),async(req,res)=>{const userId=+req.params.id,user=db.prepare('SELECT id FROM users WHERE id=? AND is_active=1').get(userId);if(!user)return res.status(404).send('User not found.');const active=db.prepare('SELECT COUNT(*) count FROM push_subscriptions WHERE user_id=? AND enabled=1').get(userId).count;if(active)return res.redirect('/admin/notification-users?message='+encodeURIComponent('That user already has an active notification device.'));await notifyUser(userId,{type:'notification_setup_reminder',title:'Enable portal notifications',message:'Please enable notifications on this device so you do not miss calendar events and reminders.',url:'/notification-settings',entityType:'notification_setup_reminder',entityId:Date.now(),createdBy:req.session.user.id},{dedupe:false});res.redirect('/admin/notification-users?message='+encodeURIComponent('In-portal reminder sent.'))});
router.post('/admin/notification-users/send-pitis',requireRole('admin'),async(req,res)=>{const sendTo=String(req.body.send_to||'selected'),requested=Array.isArray(req.body.user_ids)?req.body.user_ids:[req.body.user_ids],ids=Array.from(new Set(requested.map(Number).filter(Number.isInteger)));let users;if(sendTo==='all'){users=db.prepare('SELECT id FROM users WHERE is_active=1 ORDER BY id').all()}else{if(!ids.length)return res.redirect('/admin/notification-users?message='+encodeURIComponent('Select at least one user.'));const placeholders=ids.map(()=>'?').join(',');users=db.prepare(`SELECT id FROM users WHERE is_active=1 AND id IN (${placeholders}) ORDER BY id`).all(...ids)}const batchId=Date.now();await Promise.all(users.map(user=>notifyUser(user.id,{type:'pitis_app_invite',title:'PITIS',message:'Open and install PITIS for quick student awards and deductions.',url:'/pwa',entityType:'pitis_app_invite',entityId:batchId+Number(user.id),createdBy:req.session.user.id},{dedupe:false})));res.redirect('/admin/notification-users?message='+encodeURIComponent(`PITIS sent to ${users.length} active user${users.length===1?'':'s'}.`))});
router.get('/reminders',(req,res)=>{const user=req.session.user,staff=db.prepare("SELECT id,display_name,role FROM users WHERE is_active=1 AND role IN ('admin','teacher','staff') ORDER BY display_name").all(),items=user.role==='admin'?db.prepare('SELECT r.*,u.display_name assigned_name FROM reminders r JOIN users u ON u.id=r.assigned_to ORDER BY r.status,r.due_at').all():db.prepare('SELECT r.*,u.display_name assigned_name FROM reminders r JOIN users u ON u.id=r.assigned_to WHERE r.assigned_to=? OR r.created_by=? ORDER BY r.status,r.due_at').all(user.id,user.id);res.render('reminders',{items,staff})});
router.post('/reminders',async(req,res)=>{const user=req.session.user,assignedTo=+req.body.assigned_to,title=String(req.body.title||'').trim(),dueAt=String(req.body.due_at||'').trim()||null;if(!title||!db.prepare("SELECT 1 FROM users WHERE id=? AND is_active=1 AND role IN ('admin','teacher','staff')").get(assignedTo))return res.status(400).send('A title and valid assignee are required.');const now=dayjs().toISOString(),result=db.prepare('INSERT INTO reminders(title,details,due_at,assigned_to,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(title,String(req.body.details||'').trim(),dueAt,assignedTo,user.id,now,now);await notifyUser(assignedTo,{type:'reminder_assigned',title:'New Reminder',message:`You have been assigned: ${title}`,url:`/reminders#reminder-${result.lastInsertRowid}`,entityType:'reminder',entityId:Number(result.lastInsertRowid),createdBy:user.id});db.prepare('UPDATE reminders SET assigned_notified_at=? WHERE id=?').run(dayjs().toISOString(),result.lastInsertRowid);res.redirect('/reminders')});
router.post('/reminders/:id/complete',(req,res)=>{db.prepare("UPDATE reminders SET status='completed',updated_at=? WHERE id=? AND (assigned_to=? OR created_by=?)").run(dayjs().toISOString(),+req.params.id,req.session.user.id,req.session.user.id);res.redirect('/reminders')});
router.get('/admin/notification-diagnostics',requireRole('admin'),(_req,res)=>res.json({active:true,vapidConfigured:configured(),subscriptions:db.prepare('SELECT COUNT(*) count FROM push_subscriptions WHERE enabled=1').get().count,usersEnabled:db.prepare('SELECT COUNT(DISTINCT user_id) count FROM push_subscriptions WHERE enabled=1').get().count,usersWithoutDevices:db.prepare('SELECT COUNT(*) count FROM users u WHERE u.is_active=1 AND NOT EXISTS (SELECT 1 FROM push_subscriptions ps WHERE ps.user_id=u.id AND ps.enabled=1)').get().count,delivery:db.prepare("SELECT status,COUNT(*) count FROM notification_delivery_log GROUP BY status").all()}));
module.exports=router;
