const webpush=require('web-push');
const {getMaintenanceState}=require('./maintenanceService');
const dayjs=require('dayjs');
const {db}=require('../db/init');
const {buildWeeklySummary}=require('./pitisProgressService');
const {buildOfficialWeeks}=require('./sipPitisDashboardService');

function safeUrl(value){const url=String(value||'/').trim();return url.startsWith('/')&&!url.startsWith('//')?url:'/';}
function initializeNotificationTables(){db.exec(`
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,url TEXT NOT NULL DEFAULT '/',entity_type TEXT,entity_id INTEGER,priority TEXT NOT NULL DEFAULT 'normal',metadata TEXT,created_by INTEGER,created_at TEXT NOT NULL,read_at TEXT,push_sent_at TEXT,expires_at TEXT,UNIQUE(user_id,type,entity_type,entity_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id,read_at);
CREATE TABLE IF NOT EXISTS push_subscriptions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,endpoint TEXT NOT NULL UNIQUE,p256dh TEXT NOT NULL,auth TEXT NOT NULL,device_name TEXT,browser TEXT,platform TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions(user_id,enabled);
CREATE TABLE IF NOT EXISTS notification_preferences(user_id INTEGER PRIMARY KEY,calendar_tag INTEGER NOT NULL DEFAULT 1,calendar_event_time INTEGER NOT NULL DEFAULT 1,calendar_15_minutes INTEGER NOT NULL DEFAULT 1,calendar_1_hour INTEGER NOT NULL DEFAULT 1,calendar_1_day INTEGER NOT NULL DEFAULT 1,calendar_3_days INTEGER NOT NULL DEFAULT 1,calendar_5_days INTEGER NOT NULL DEFAULT 1,reminder_assigned INTEGER NOT NULL DEFAULT 1,reminder_due_soon INTEGER NOT NULL DEFAULT 1,reminder_overdue INTEGER NOT NULL DEFAULT 1,pitis_progress INTEGER NOT NULL DEFAULT 1,system_important INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS pitis_notification_events(event_date TEXT NOT NULL,event_type TEXT NOT NULL,winner_user_id INTEGER,created_at TEXT NOT NULL,PRIMARY KEY(event_date,event_type),FOREIGN KEY(winner_user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS calendar_notification_jobs(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL,user_id INTEGER NOT NULL,offset_minutes INTEGER NOT NULL,due_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',sent_at TEXT,created_at TEXT NOT NULL,UNIQUE(event_id,user_id,offset_minutes),FOREIGN KEY(event_id) REFERENCES calendar_events(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_calendar_notification_jobs_due ON calendar_notification_jobs(status,due_at);
CREATE TABLE IF NOT EXISTS notification_delivery_log(id INTEGER PRIMARY KEY AUTOINCREMENT,notification_id INTEGER,subscription_id INTEGER,status TEXT NOT NULL,http_status INTEGER,created_at TEXT NOT NULL,FOREIGN KEY(notification_id) REFERENCES notifications(id) ON DELETE SET NULL,FOREIGN KEY(subscription_id) REFERENCES push_subscriptions(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS reminders(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,details TEXT,due_at TEXT,assigned_to INTEGER NOT NULL,created_by INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'open',assigned_notified_at TEXT,due_notified_at TEXT,overdue_notified_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_reminders_assignee_due ON reminders(assigned_to,status,due_at);
`);const columns=db.prepare('PRAGMA table_info(notification_preferences)').all().map(row=>row.name);if(!columns.includes('calendar_3_days'))db.exec('ALTER TABLE notification_preferences ADD COLUMN calendar_3_days INTEGER NOT NULL DEFAULT 1');if(!columns.includes('calendar_5_days'))db.exec('ALTER TABLE notification_preferences ADD COLUMN calendar_5_days INTEGER NOT NULL DEFAULT 1');if(!columns.includes('pitis_progress'))db.exec('ALTER TABLE notification_preferences ADD COLUMN pitis_progress INTEGER NOT NULL DEFAULT 1');if(!columns.includes('pitis_0930_reminder'))db.exec('ALTER TABLE notification_preferences ADD COLUMN pitis_0930_reminder INTEGER NOT NULL DEFAULT 1');if(!columns.includes('pitis_first_award'))db.exec('ALTER TABLE notification_preferences ADD COLUMN pitis_first_award INTEGER NOT NULL DEFAULT 1');migratePendingCalendarJobs()}
function migratePendingCalendarJobs(){const rows=db.prepare("SELECT event_id,user_id,due_at FROM calendar_notification_jobs WHERE offset_minutes=0 AND status='pending'").all(),replace=db.transaction(items=>{const remove=db.prepare("DELETE FROM calendar_notification_jobs WHERE event_id=? AND user_id=? AND status='pending'"),add=db.prepare('INSERT OR IGNORE INTO calendar_notification_jobs(event_id,user_id,offset_minutes,due_at,created_at) VALUES(?,?,?,?,?)'),now=dayjs();for(const row of items){const base=dayjs(row.due_at);remove.run(row.event_id,row.user_id);for(const offset of [0,4320,7200]){const due=base.subtract(offset,'minute');if(!due.isBefore(now,'minute'))add.run(row.event_id,row.user_id,offset,due.toISOString(),now.toISOString())}}});replace(rows)}
function configured(){const pub=String(process.env.VAPID_PUBLIC_KEY||''),priv=String(process.env.VAPID_PRIVATE_KEY||''),subject=String(process.env.VAPID_SUBJECT||'');if(pub&&priv&&subject){webpush.setVapidDetails(subject,pub,priv);return true}return false}
async function sendPushToUser(userId,notification){if(!configured())return;const rows=db.prepare('SELECT * FROM push_subscriptions WHERE user_id=? AND enabled=1').all(userId);await Promise.allSettled(rows.map(async sub=>{try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},JSON.stringify({title:notification.title,body:notification.message,url:safeUrl(notification.url),type:notification.type,notificationId:notification.id}),{TTL:86400});db.prepare('INSERT INTO notification_delivery_log(notification_id,subscription_id,status,created_at) VALUES(?,?,?,?)').run(notification.id,sub.id,'delivered',dayjs().toISOString())}catch(error){const status=Number(error.statusCode||0);db.prepare('INSERT INTO notification_delivery_log(notification_id,subscription_id,status,http_status,created_at) VALUES(?,?,?,?,?)').run(notification.id,sub.id,status===404||status===410?'expired':'failed',status||null,dayjs().toISOString());if(status===404||status===410)db.prepare('UPDATE push_subscriptions SET enabled=0,updated_at=? WHERE id=?').run(dayjs().toISOString(),sub.id)}}));db.prepare('UPDATE notifications SET push_sent_at=? WHERE id=?').run(dayjs().toISOString(),notification.id)}
async function notifyUser(userId,data,{dedupe=true}={}){const user=db.prepare('SELECT id FROM users WHERE id=? AND is_active=1').get(userId);if(!user)return null;const now=dayjs().toISOString();let info;try{info=db.prepare('INSERT INTO notifications(user_id,type,title,message,url,entity_type,entity_id,priority,metadata,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(userId,String(data.type||'system'),String(data.title||'Notification').slice(0,160),String(data.message||'').slice(0,1000),safeUrl(data.url),data.entityType||null,data.entityId||null,data.priority||'normal',data.metadata?JSON.stringify(data.metadata):null,data.createdBy||null,now)}catch(error){if(dedupe&&String(error.code).includes('UNIQUE'))return null;throw error}const notification=db.prepare('SELECT * FROM notifications WHERE id=?').get(info.lastInsertRowid);const prefs=db.prepare('SELECT * FROM notification_preferences WHERE user_id=?').get(userId)||{};const key=data.preferenceKey||{calendar_tag:'calendar_tag',calendar_reminder:'calendar_event_time',reminder_assigned:'reminder_assigned',reminder_due:'reminder_due_soon'}[notification.type];if(!key||prefs[key]!==0)await sendPushToUser(userId,notification);return notification}
function scheduleEvent(eventId,userIds,eventDate,eventTime='09:00',offsets=[0,4320,7200]){const base=dayjs(`${eventDate}T${eventTime||'09:00'}:00`),now=dayjs(),createdAt=now.toISOString(),add=db.prepare('INSERT OR IGNORE INTO calendar_notification_jobs(event_id,user_id,offset_minutes,due_at,created_at) VALUES(?,?,?,?,?)');db.prepare("DELETE FROM calendar_notification_jobs WHERE event_id=? AND status='pending'").run(eventId);for(const userId of userIds)for(const offset of offsets){const due=base.subtract(offset,'minute');if(!due.isBefore(now,'minute'))add.run(eventId,userId,offset,due.toISOString(),createdAt)}}
let timer;
async function processReminders(){const now=dayjs(),rows=db.prepare("SELECT * FROM reminders WHERE status='open' AND due_at IS NOT NULL AND (due_notified_at IS NULL OR overdue_notified_at IS NULL) ORDER BY due_at LIMIT 100").all();for(const row of rows){const due=dayjs(row.due_at);if(!row.due_notified_at&&due.diff(now,'minute')<=60&&due.isAfter(now)){await notifyUser(row.assigned_to,{type:'reminder_due',title:'Reminder due soon',message:`${row.title} is due soon.`,url:`/reminders#reminder-${row.id}`,entityType:'reminder_due',entityId:row.id});db.prepare('UPDATE reminders SET due_notified_at=? WHERE id=? AND due_notified_at IS NULL').run(now.toISOString(),row.id)}else if(!row.overdue_notified_at&&due.isBefore(now)){await notifyUser(row.assigned_to,{type:'reminder_overdue',title:'Overdue reminder',message:`${row.title} is overdue.`,url:`/reminders#reminder-${row.id}`,entityType:'reminder_overdue',entityId:row.id});db.prepare('UPDATE reminders SET overdue_notified_at=? WHERE id=? AND overdue_notified_at IS NULL').run(now.toISOString(),row.id)}}}
async function processWeeklyPitisSummaries(){const users=db.prepare("SELECT id FROM users WHERE is_active=1 AND role='teacher' AND COALESCE(user_type,role)='teacher'").all();for(const user of users){const summary=buildWeeklySummary(user.id);if(!summary)continue;const met=summary.requiredDays>0&&summary.activeDays>=summary.requiredDays;await notifyUser(user.id,{type:'pitis_weekly_summary',title:`Weekly PITIS summary · Week ${summary.weekNumber}`,message:`${summary.activeDays} of ${summary.requiredDays} target days (${summary.percentage}%). ${summary.pointsAwarded} PITIS awarded to ${summary.studentsRewarded} student${summary.studentsRewarded===1?'':'s'}. ${met?'Target met.':'Keep building consistency next week.'}`,url:'/teacher/dashboard#pitis-progress',entityType:'pitis_week',entityId:summary.entityId,preferenceKey:'pitis_progress'});}}
function isOfficialSchoolDay(dateValue){return buildOfficialWeeks(dateValue).some(week=>week.days.some(day=>day.date===dateValue&&day.type==='school_day'))}
function activeTeachers(){return db.prepare("SELECT id,display_name,username FROM users WHERE is_active=1 AND role='teacher' AND COALESCE(user_type,role)='teacher' ORDER BY id").all()}
function activePitisUsers(){return db.prepare("SELECT id,display_name,username FROM users WHERE is_active=1 AND role IN ('teacher','staff','admin') ORDER BY id").all()}
async function processPitisDailyNotifications(nowValue=dayjs()){
  const now=dayjs(nowValue);if(!now.isValid())return {schoolDay:false,reminders:0,firstAward:false};
  const dateValue=now.format('YYYY-MM-DD');if(!isOfficialSchoolDay(dateValue))return {schoolDay:false,reminders:0,firstAward:false};
  const entityId=Number(dateValue.replace(/-/g,''));let reminders=0,firstAward=false;
  const first=db.prepare(`SELECT pl.id,pl.awarded_by,u.display_name,u.username,u.role,COALESCE(u.user_type,u.role) user_type FROM point_logs pl JOIN users u ON u.id=pl.awarded_by WHERE pl.points>0 AND date(pl.awarded_at,'+8 hours')=date(?) ORDER BY pl.awarded_at,pl.id LIMIT 1`).get(dateValue);
  if(first&&first.role==='teacher'&&first.user_type==='teacher'){
    const claim=db.prepare("INSERT OR IGNORE INTO pitis_notification_events(event_date,event_type,winner_user_id,created_at) VALUES(?,'first_award',?,?)").run(dateValue,first.awarded_by,now.toISOString());
    if(claim.changes){
      firstAward=true;const winnerName=first.display_name||first.username||'A teacher';
      for(const user of activePitisUsers()){
        const winner=Number(user.id)===Number(first.awarded_by);
        await notifyUser(user.id,{type:'pitis_first_award',title:winner?'First PITIS award today!':"Today's PITIS recognition has started",message:winner?`Great start, ${winnerName}! You made the school's first PITIS award today. Keep the positive momentum going.`:`${winnerName} made the first PITIS award today. Follow their lead and recognise a student when you can.`,url:'/pwa',entityType:'pitis_first_award_day',entityId,preferenceKey:'pitis_first_award'});
      }
    }
  }
  if(now.hour()>9||(now.hour()===9&&now.minute()>=30)){
    for(const teacher of activeTeachers()){
      const awarded=db.prepare("SELECT 1 FROM point_logs WHERE awarded_by=? AND points>0 AND date(awarded_at,'+8 hours')=date(?) LIMIT 1").get(teacher.id,dateValue);
      if(awarded)continue;
      const notification=await notifyUser(teacher.id,{type:'pitis_0930_reminder',title:'A positive start is still waiting',message:'A small recognition can brighten a student’s day. Award your first PITIS when you are ready.',url:'/pwa',entityType:'pitis_0930_day',entityId,preferenceKey:'pitis_0930_reminder'});
      if(notification)reminders+=1;
    }
  }
  return {schoolDay:true,reminders,firstAward};
}
function initializeNotificationScheduler(){if(timer)return;const run=async()=>{if(getMaintenanceState())return;const jobs=db.prepare("SELECT j.*,e.title,e.event_date FROM calendar_notification_jobs j JOIN calendar_events e ON e.id=j.event_id WHERE j.status='pending' AND j.due_at<=? AND e.is_deleted=0 ORDER BY j.due_at LIMIT 100").all(dayjs().toISOString());for(const job of jobs){const claimed=db.prepare("UPDATE calendar_notification_jobs SET status='processing' WHERE id=? AND status='pending'").run(job.id);if(!claimed.changes)continue;try{const reminder=job.offset_minutes===7200?{phrase:'starts in 5 days',preferenceKey:'calendar_5_days'}:job.offset_minutes===4320?{phrase:'starts in 3 days',preferenceKey:'calendar_3_days'}:{phrase:'is today',preferenceKey:'calendar_event_time'};await notifyUser(job.user_id,{type:'calendar_reminder',title:'Calendar Reminder',message:`${job.title} ${reminder.phrase}.`,url:`/teacher/calendar?event=${job.event_id}`,entityType:'calendar_reminder_job',entityId:job.id,preferenceKey:reminder.preferenceKey});db.prepare("UPDATE calendar_notification_jobs SET status='sent',sent_at=? WHERE id=?").run(dayjs().toISOString(),job.id)}catch{db.prepare("UPDATE calendar_notification_jobs SET status='pending' WHERE id=? AND status='processing'").run(job.id)}}await processReminders();await processWeeklyPitisSummaries();await processPitisDailyNotifications()};run().catch(error=>console.error('Notification scheduler error:',error));timer=setInterval(()=>run().catch(error=>console.error('Notification scheduler error:',error)),60000);timer.unref?.()}
module.exports={initializeNotificationTables,initializeNotificationScheduler,notifyUser,scheduleEvent,safeUrl,configured,processPitisDailyNotifications,isOfficialSchoolDay};
